name: Run Cypress Tests
on: [push]
jobs:
  install:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Cypress run
        uses: cypress-io/github-action@v3
        with:
          start: npx cypress run --config video=false
          
          